
block = (n) => n * 32;

class Level{
    constructor(o = {
        name: new String,
        tiles: new Array,
        doors: new Array,

        
    }) {
        this.name = o.name;
        this.tiles = o.tiles;
        this.doors = o.doors;

        return this;
    }


    draw(){
        this.tiles.forEach(tile => tile.draw());
    }
}


const level = [
    {
        name: "The Well",
        layout: [
            "XXXXX--XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X    --    XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X--        XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X       ---XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X---       XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X    --    XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X        --XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X--        XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X          XXXXXXXXXXXXXXXXXXXXX",
            "X    --    XX        XXXXXXXXXXX",
            "X          XX  XXXX  XXXXXXXXXXX",
            "X          XX  XXXX           XX",
            "X          XX  XXXXXXXXX      XX",
            "X       ---XX  XXXXXXXXX    @ XX",
            "X          XX  XXXXXXXXXXXXXXXXX",
            "X          XX  XXXXXXXXXXXXXXXXX",
            "X---       XX  XXXXXXXXXXXXXXXXX",
            "X              XXXXXXXXXXXXXXXXX",
            "X              XXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ],
        advancedLayer: [
            {
                type: "E",
                x: block(5),
                y: block(0),
                width: block(2),
                height: block(0),
                entry: block(1),
                exit: 1,
                exitX: block(6),
                exitY: block(81.5),
            },
        ],
        npcs: [
            //new SpikeGuard(block(3), block(15)),
        ]
    }, {
        name: "Toybox",
        layout: [

            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X      G                G                                   G          X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "                                                                        ",
            "X-            XXX               >>           <<   XXX               XXXX",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "X                    G                 G                               X",
            "X                                                                      X",
            "X                                                        XXXXXX        X",
            "X                                                                      X",
            "X                                                                      X",
            "X                                                                      X",
            "XXXXXXXXXX                   XXX                      G                X",
            "X        X                    L                                        X",
            "X                                                                      X",
            "X     vv                                                               X",
            "X        XXXXXXXXXXXXXX                                                X",
            "X        X            X                        G                       X",
            "X    MMMMX            X                                                X",
            "X    XXXXX                                                             X",
            "X                                                                      X",
            "X                                                                      X",
            "XXXXXXXXXXXXXMMMMMMXXXX      XXXXXXXXXXX                     XXX-------X",
            "XXXXXXXXXXXXXXXXXXXXXXX        G     G                        G        X",
            "XX             L    X                                                  X",
            "XX                  X                                                  X",
            "XX                  X  ^^vv                                            X",
            "XX    vv                                                               X",
            "XX       XXX                                                           X",
            "XX       XXX                                                           X",
            "XX       XXX >>     XXXMMMMXXX                     XXX                 X",
            "XX       XXX        XXXXXXXXXX---   ---X                               X",
            "XX       XXX        XXXXXXXXXX         X     XX                        X",
            "XX       XXX        X        X         X     XX                        X",
            "XX                  X        X         X     XX                        X",
            "XX ^^               X    @   X   ---   X                               X",
            "                        XX                                              ",
            "                       XXXX                                             ",
            "XXXXX--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        ],
        advancedLayer: [
            {
                type: "E",
                x: block(0),
                y: block(80),
                width: block(0),
                height: block(2),
                entry: block(1),
                exit: 2,
                exitX: block(81.5),
                exitY: block(9.5),
            }, {
                type: "E",
                x: block(72),
                y: block(80),
                width: block(0),
                height: block(2),
                entry: block(1),
                exit: 3,
                exitX: block(.5),
                exitY: block(10.5),
            },
            {
                type: "E",
                x: block(72.5),
                y: block(5),
                width: block(0),
                height: block(2),
                entry: block(1),
                exit: 5,
                exitX: block(.5),
                exitY: block(1.5),
            },
            {
                type: "E",
                x: block(-.5),
                y: block(5),
                width: block(0),
                height: block(1),
                entry: block(1),
                exit: 6,
                exitX: block(42),
                exitY: block(6.5),
            }
        ],
        npcs: [
            //new TestSign(5, 90, () => dialogue.debugMsgs[0]),
            // new Bogus(block(30), block(79), () => dialogue.playDialogue(bogusDialogues[0])) //block(20), block(20)),
            // new LaserTurret(block(20), block(31)),
            //new Roamer(30, 31)
        ]
    }, {
        name: "GA-19",
        layout: [
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                X",
            "X                                                                                 ",
            "X                                                                                 ",
            "X                             X----XXXX  >>        <<  XXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                             X    XXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                             X    XXXXMMMMMMMMMMMMMMMMXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                             X----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X        @                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        ],
        advancedLayer: [
            {
                type: "E",
                x: block(81.99),
                y: block(8),
                width: block(0),
                height: block(2),
                entry: block(1),
                exit: 1,
                exitX: block(.5),
                exitY: block(81.5),
            }
        ]
    }, {
        name: "MNKO Swinging Course - Hall",
        layout: [
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                               XXX                                                             XXX",
            "X                               XXX                                                             XXX",
            "X            G                  XXX                                                             XXX",
            "X                               XXX                G                                            XXX",
            "X                               XXX                                                             XXX",
            "X                               XXX                                                 XXXXXXXXX   XXX",
            "X                               XXX                                                 XXXWWWWG    XXX",
            "X                               XXX                                                 XXX         XXX",
            "                       XXXXXX   XXX                            G            G       XXX         XXX",
            "  @                    XXXXXX   XXX   XXXXXX                                        XXX         XXX",
            "XXXX                   XXXXXX    G    XXXXXX                                        XXX         XXX",
            "XXXX                   XXXXXX         XXXXXX                                        XXX   MMMMMMXXX",
            "XXXX                   XXXXXX         XXXXXX                                        XXX   XXXXXXXXX",
            "XXXX                   XXXXXX         XXXXXX                                        XXX            ",
            "XXXX                   XXXXXX         XXXXXX                                        XXX            ",
            "XXXX                   XXXXXX         XXXXXX                                        XXX            ",
            "XXXX                   XXXXXX         XXXXXX                                        XXXXXXXXXXXXXXX",
        ],
        advancedLayer: [
            {
                type: "E",
                x: block(0),
                y: block(10),
                width: block(0),
                height: block(2),
                exit: 1,
                exitX: block(71.5),
                exitY: block(81.5),
            }, {
                type: "E",
                x: block(99.5),
                y: block(14),
                width: block(0),
                height: block(3),
                exit: 4,
                exitX: block(0),
                exitY: block(53.5)
            }
        ]
    }, {
        name: "MNKO Swinging Course - Tower",
        layout: [
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "    XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX         G      G         XXX",
            "XXXXXXX                  XXX-XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                  XXX-XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXXMMMMMMMMMMMMMMMMMMXXX-XXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                  XXX-XXX",
            "XXXXXXX                  XXX XXX",
            "XXXXXXX                      XXX",
            "XXXXXXX     XXX       XXXXXXXXXX",
            "XXXXXXX     XXXMMMMMMMXXXXXXXXXX",
            "XXXXXXX     XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXX     XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXX     XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXX     WWWWWWWWWWWWWXXXXXXX",
            "XXXXXXX         G        XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXXMMMMMMMMMMMMM     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX     XXXXXXX",
            "XXXXXXXWWWWWWWWWWWWW     XXXXXXX",
            "XXXXXXX         G        XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "                         XXXXXXX",
            "                         XXXXXXX",
            "        @                XXXXXXX",
            "XXXXXXX---               XXXXXXX",
            "XXXXXXX                  XXXXXXX",
            "XXXXXXXMMMMMMMMMMMMMMMMMMXXXXXXX",
        ],
        advancedLayer: [{
            type: "E",
            x: block(-.5),
            y: block(51),
            width: block(0),
            height: block(3),
            exit: 3,
            exitX: block(98.5),
            exitY: block(16.5)
        },
        {
            type: "E",
            x: block(-.5),
            y: block(1),
            width: block(0),
            height: block(1),
            exit: 5,
            exitX: block(42.5),
            exitY: block(1.5)
        }

        ],
        npcs: [
            //new SpikeGuard(block(10), block(10)),
        ]
    }, {
        name: "MNKO Swinging Course - Vents",
        layout: [
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "                                         @ ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ],
        advancedLayer: [{
            type: "E",
            x: block(43.5),
            y: block(1),
            width: block(0),
            height: block(1),
            exit: 4,
            exitX: block(0),
            exitY: block(1.5)
        }, {
            type: "E",
            x: block(-.5),
            y: block(1),
            width: block(0),
            height: block(1),
            exit: 1,
            exitX: block(71),
            exitY: block(5.5)
        },]
    }, {
        name: "GA-19 - Vents",
        layout: [
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXX                                    XXX",
            "XXX                                    XXX",
            "XXX                                    XXX",
            "XXX   XXX                        XXX   XXX",
            "XXX   XXX       XXX     XXX      XXX   XXX",
            "X                                       @ ",
            "XXXXXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXXXXXX",
        ],
        advancedLayer: [{
            type: "E",
            x: block(42.5),
            y: block(6),
            width: block(0),
            height: block(1),
            exit: 1,
            exitX: block(0),
            exitY: block(5.5)
        }]
    }, {
        name: "Adv Layer Testing",
        layout: [
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X                  X",
            "X            X     X",
            "X GX         X  G  X",
            "X            X     X",
            "X         @  X     X",
            "XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXX",
        ],
        advancedLayer: [],
    }, {
        name: "Light Test",
        layout: [
            "                                                                                      ",
            "                                          L                                           ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                                                                      ",
            "                                      ---------------                                 ",
            "                                                                                      ",
            "                                                                                      ",
            "                                      ---------------                                 ",
            " @                                                                                    ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ],
        advancedLayer: []
    }];

